name: "tss2-fapi-rs-swtpm"

services:
  swtpm:
    build:
      context: ./
      dockerfile: swtpm.Dockerfile
      args:
        BASE_VERSION: ${BASE_VERSION_SWTPM:-r24@sha256:a40eb85ab67cfdb3c398d36541046925d1aa4bf822dc0036bb187d6c48580f15}
    volumes:
      - log:/var/log/swtpm:rw
    tmpfs:
      - /var/lib/swtpm
      - /var/lib/swtpm-localca
    ports:
      - "2321:2321"
      - "2322:2322"
    restart: unless-stopped
    stop_signal: SIGKILL

volumes:
  log:
