name: "tss2-fapi-rs-swtpm"

services:
  swtpm:
    build:
      context: ./
      dockerfile: swtpm.Dockerfile
      args:
        BASE_VERSION: ${BASE_VERSION_SWTPM:-r29@sha256:17fa49a22694ca52fa86c24f9907149d8bcf6d2d79909b5105410560104fb016}
    volumes:
      - log:/var/log/swtpm:rw
    tmpfs:
      - /var/lib/swtpm
      - /var/lib/swtpm-localca
    ports:
      - "2321:2321"
      - "2322:2322"
    restart: unless-stopped
    stop_signal: SIGKILL

volumes:
  log:
