name: "tss2-fapi-rs-swtpm"

services:
  swtpm:
    build:
      context: ./
      dockerfile: swtpm.Dockerfile
      args:
        BASE_VERSION: ${BASE_VERSION_SWTPM:-r26@sha256:c80dc0a4b6c3a1ab46be81931344178d5d3da3c21cfd00990c948c7f59a25557}
    volumes:
      - log:/var/log/swtpm:rw
    tmpfs:
      - /var/lib/swtpm
      - /var/lib/swtpm-localca
    ports:
      - "2321:2321"
      - "2322:2322"
    restart: unless-stopped
    stop_signal: SIGKILL

volumes:
  log:
